<a href="https://colab.research.google.com/github/BelKaty/BelKaProject/blob/main/HW5_NN_AI.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import re

In [2]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [3]:
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [4]:
len(text)

205

In [5]:
num_characters = 34 #33 буквы + пробел

In [6]:
import keras
from keras.preprocessing.text import Tokenizer

In [7]:
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [8]:
tokenizer.fit_on_texts(text)

In [10]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [11]:
inp_chars = 6 #
data = tokenizer.texts_to_matrix(text)

In [12]:
data[1]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
n = data.shape[0]-inp_chars
n  #размер обучающего множества

199

In [14]:
import numpy as np

In [15]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [16]:
len(X)

199

In [17]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [18]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
from keras.layers import *
from keras.models import Sequential

In [20]:
model = Sequential()
model.add(Input((inp_chars, num_characters)))
model.add(SimpleRNN(500, activation='tanh'))
model.add(Dense(num_characters, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 500)               267500    
                                                                 
 dense (Dense)               (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [21]:
from keras.layers import SimpleRNN


In [22]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)

Epoch 1/100
7/7 [==============================] - 1s 17ms/step - loss: 3.3780 - accuracy: 0.0955
Epoch 2/100
7/7 [==============================] - 0s 16ms/step - loss: 2.4025 - accuracy: 0.3015
Epoch 3/100
7/7 [==============================] - 0s 16ms/step - loss: 1.8917 - accuracy: 0.4523
Epoch 4/100
7/7 [==============================] - 0s 19ms/step - loss: 1.5469 - accuracy: 0.5377
Epoch 5/100
7/7 [==============================] - 0s 21ms/step - loss: 1.2256 - accuracy: 0.6332
Epoch 6/100
7/7 [==============================] - 0s 19ms/step - loss: 1.0224 - accuracy: 0.7035
Epoch 7/100
7/7 [==============================] - 0s 16ms/step - loss: 0.8817 - accuracy: 0.7487
Epoch 8/100
7/7 [==============================] - 0s 15ms/step - loss: 0.7450 - accuracy: 0.7940
Epoch 9/100
7/7 [==============================] - 0s 15ms/step - loss: 0.6958 - accuracy: 0.8090
Epoch 10/100
7/7 [==============================] - 0s 15ms/step - loss: 0.6085 - accuracy: 0.8191
Epoch 11/100
7/7 [=

In [23]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding

    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)

    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении

    inp_str += d # дописываем строку

  return inp_str

In [24]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 20ms/step
утренновтввд  а гяислптс пориеев ы нпчерьертв свыю споло


## Слова

In [25]:
from keras.preprocessing.text import Tokenizer
from keras.models import Sequential
from keras.layers import Embedding, SimpleRNN, Dense

In [26]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    texts = f.read()
    texts = texts.replace('\ufeff', '')

In [27]:
texts

'Вы — лучший ответ на проблемы, которые возникли в понедельник.\nДумайте позитивно и верьте в свою способность достигать отличных результатов.\nЕсли вы смогли в понедельник подняться с постели, значит вы супер герой.'

In [28]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–" —#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»', lower=True, split=' ', char_level=False)

tokenizer.fit_on_texts([texts])

In [29]:
sequences = tokenizer.texts_to_sequences([texts])[0]
vocab_size = len(tokenizer.word_index) + 1

In [30]:
sequences

[1,
 4,
 5,
 6,
 7,
 8,
 9,
 2,
 3,
 10,
 11,
 12,
 13,
 2,
 14,
 15,
 16,
 17,
 18,
 19,
 1,
 20,
 2,
 3,
 21,
 22,
 23,
 24,
 1,
 25,
 26]

In [31]:
vocab_size

27

In [32]:
inp_words = 3
X = []
Y = []
for i in range(len(sequences) - inp_words):
    X.append(sequences[i:i + inp_words])
    Y.append(sequences[i + inp_words])

X = np.array(X)
Y = np.array(Y)

In [33]:
X

array([[ 1,  4,  5],
       [ 4,  5,  6],
       [ 5,  6,  7],
       [ 6,  7,  8],
       [ 7,  8,  9],
       [ 8,  9,  2],
       [ 9,  2,  3],
       [ 2,  3, 10],
       [ 3, 10, 11],
       [10, 11, 12],
       [11, 12, 13],
       [12, 13,  2],
       [13,  2, 14],
       [ 2, 14, 15],
       [14, 15, 16],
       [15, 16, 17],
       [16, 17, 18],
       [17, 18, 19],
       [18, 19,  1],
       [19,  1, 20],
       [ 1, 20,  2],
       [20,  2,  3],
       [ 2,  3, 21],
       [ 3, 21, 22],
       [21, 22, 23],
       [22, 23, 24],
       [23, 24,  1],
       [24,  1, 25]])

In [34]:
Y

array([ 6,  7,  8,  9,  2,  3, 10, 11, 12, 13,  2, 14, 15, 16, 17, 18, 19,
        1, 20,  2,  3, 21, 22, 23, 24,  1, 25, 26])

In [35]:
model = Sequential([
    Embedding(vocab_size, 50, input_length=inp_words),
    SimpleRNN(128),
    Dense(vocab_size, activation='softmax')
])

In [36]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [37]:
history = model.fit(X, Y, batch_size=32, epochs=20)

Epoch 1/20
1/1 [==============================] - 1s 1s/step - loss: 3.2866 - accuracy: 0.0357
Epoch 2/20
1/1 [==============================] - 0s 15ms/step - loss: 3.2560 - accuracy: 0.1429
Epoch 3/20
1/1 [==============================] - 0s 16ms/step - loss: 3.2253 - accuracy: 0.3214
Epoch 4/20
1/1 [==============================] - 0s 14ms/step - loss: 3.1942 - accuracy: 0.4643
Epoch 5/20
1/1 [==============================] - 0s 17ms/step - loss: 3.1626 - accuracy: 0.6071
Epoch 6/20
1/1 [==============================] - 0s 16ms/step - loss: 3.1302 - accuracy: 0.6786
Epoch 7/20
1/1 [==============================] - 0s 19ms/step - loss: 3.0967 - accuracy: 0.7500
Epoch 8/20
1/1 [==============================] - 0s 15ms/step - loss: 3.0620 - accuracy: 0.7857
Epoch 9/20
1/1 [==============================] - 0s 15ms/step - loss: 3.0258 - accuracy: 0.8214
Epoch 10/20
1/1 [==============================] - 0s 16ms/step - loss: 2.9878 - accuracy: 0.8214
Epoch 11/20
1/1 [==============

In [38]:
import numpy as np
from keras.preprocessing.sequence import pad_sequences

In [39]:
def buildPhrase(text, model, tokenizer, max_len=20):
    result = text.lower()
    input_text = text
    for _ in range(max_len):
        sequence = tokenizer.texts_to_sequences([input_text])[0]
        sequence = pad_sequences([sequence], maxlen=inp_words, padding='pre')
        pred = model.predict(sequence)
        pred_index = np.argmax(pred)
        pred_word = tokenizer.index_word[pred_index]
        result += " " + pred_word
        input_text = input_text.split()[1:] + [pred_word]
        input_text = ' '.join(input_text)
    return result

In [40]:
initial_text = "позитив добавляет годы"
predicted_phrase = buildPhrase(initial_text, model, tokenizer)
print(predicted_phrase)

1/1 [==============================] - 0s 24ms/step
позитив добавляет годы понедельник понедельник понедельник в в понедельник понедельник позитивно в понедельник в позитивно понедельник понедельник в в понедельник понедельник позитивно в


В данном коде реализована функция buildPhrase, которая использует рекуррентную нейронную сеть для создания последовательности слов на основе заданного текста. Основные этапы выполнения этой функции включают:

Подготовку входных данных: Исходный текст приводится к нижнему регистру для стандартизации данных и токенизируется с использованием токенизатора, связанного с моделью.

Генерацию слов: Затем осуществляется цикл, в котором предсказывается следующее слово в последовательности. Текущая последовательность слов преобразуется в токены и производится предсказание с помощью модели.

Обновление данных: Предсказанное слово добавляется к сгенерированной последовательности, затем входной текст обновляется путем удаления первого слова и добавления предсказанного.

Завершение цикла: Этот процесс повторяется до достижения заданной длины последовательности или критерия останова.

Возврат результата: В конце функции возвращается сгенерированная последовательность слов.

Таким образом, функция buildPhrase эффективно использует рекуррентную нейронную сеть для генерации текста на основе обученных данных и представляет собой удобный инструмент для автоматического создания текста с помощью модели и токенизатора.